# Generated by Django 5.1.4 on 2025-02-26 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('chess', 'Chess'), ('catan', 'Settlers of Catan'), ('dnd', 'Dungeons & Dragons')], max_length=50)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='setup', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePiece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('piece_type', models.CharField(max_length=50)),
                ('piece_color', models.CharField(default='white', max_length=50)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField(default=0)),
                ('rotation', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pieces', to='dash.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_x', models.FloatField()),
                ('from_y', models.FloatField()),
                ('to_x', models.FloatField()),
                ('to_y', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='dash.gamepiece')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_moves', to='dash.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='RobotCommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('move', 'Move Piece'), ('camera', 'Camera Control'), ('reset', 'Reset Game'), ('system', 'System Command')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_commands', to='dash.gamesession')),
            ],
        ),
    ]
